const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const context = vm.createContext({ console });
vm.runInContext(fs.readFileSync(path.join(__dirname,'../realm-planner.js'),'utf8'), context);
let data = { locations: { home: { category: 'bases' } } };
let revision = 0;
function apply(command) {
    context.data = structuredClone(data);
    context.command = { player: 'Peter', stamp: `v${++revision}`, ...command };
    data = JSON.parse(JSON.stringify(vm.runInContext('applyRealmPlannerCommand(data, command)', context)));
}
apply({ action:'favourite', id:'home', selected:true });
apply({ action:'favourite', id:'home', player:'Jadey', selected:true });
apply({ action:'favourite', id:'home', selected:false });
assert.equal(data.favourites.Peter.home, undefined);
assert.equal(data.favourites.Jadey.home, true);
apply({ action:'category-delete', id:'bases', original:'Bases' });
assert.equal(data.locations.home.category, undefined);
for(let i=0; i<26; i++) apply({ action:'category-save', id:`category${i}`, title:`Category ${i}` });
assert.throws(() => apply({ action:'category-save', id:'overflow', title:'Extra' }), /limit reached/);
apply({ action:'category-save', id:'category0', original:'Category 0', title:'Renamed' });
for(let i=0; i<30; i++) apply({ action:'list-save', id:`list${i}`, title:`List ${i}` });
apply({ action:'list-archive', id:'list1', archived:true });
assert.throws(() => apply({ action:'list-save', id:'overflow', title:'Extra' }), /including archived/);
apply({ action:'item-save', listId:'list0', id:'iron', kind:'quantity', title:'Iron', target:128, amount:32 });
const originalRevision = data.lists.list0.items.iron.revision;
apply({ action:'quantity', listId:'list0', id:'iron', operation:'add', amount:16, revision:originalRevision });
apply({ action:'quantity', listId:'list0', id:'iron', operation:'add', amount:16, revision:originalRevision, player:'Jadey' });
assert.equal(data.lists.list0.items.iron.amount, 64, 'Both contributions count');
assert.throws(() => apply({ action:'quantity', listId:'list0', id:'iron', operation:'set', amount:1, revision:originalRevision }), /changed/);
apply({ action:'quantity', listId:'list0', id:'iron', operation:'complete', amount:0 });
assert.equal(data.lists.list0.items.iron.amount,128);
apply({ action:'quantity', listId:'list0', id:'iron', operation:'set', amount:32, revision:data.lists.list0.items.iron.revision });
assert.equal(data.lists.list0.items.iron.amount,32);
for(let i=0; i<149; i++) apply({ action:'item-save', listId:'list0', id:`item${i}`, kind:'checkbox', title:`Item ${i}` });
assert.throws(() => apply({ action:'item-save', listId:'list0', id:'extra', kind:'checkbox', title:'Extra' }), /Item limit/);
apply({ action:'item-check', listId:'list0', id:'item0', completed:true });
assert.equal(data.lists.list0.items.item0.amount,1);
apply({ action:'item-check', listId:'list0', id:'item0', completed:false });
assert.equal(data.lists.list0.items.item0.amount,0);
assert.throws(() => apply({ action:'list-save', id:'list0', title:'a'.repeat(81) }), /80 characters/);
assert.throws(() => apply({ action:'list-save', id:'list0', title:'Title', note:'a'.repeat(1001) }), /1,000 characters/);
console.log('PASS: personal favourites, category deletion, shared caps, archived-list limits, simultaneous quantity contributions, stale edits, completion/reopening and text limits.');
